services:
  - type: worker  # <-- đây là quan trọng, đổi từ "web" thành "worker"
    name: entry247-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python entry247_bot.py"
    autoDeploy: true
    branch: main
